/* Generated by gulp-vuesplit - Edit the vue file instead. */
/* eslint-disable */
export default "<div class=message-1be8ba25><h1 class=title-1be8ba25>{{msg}}</h1><p>Intro text<div class=buttonbar-1be8ba25><button class=cancel-1be8ba25>Cancel</button> <button class=okay-1be8ba25>Save</button></div></div>"